import { Types } from "mongoose";

export interface IRegister {
  _id?: Types.ObjectId;
  name?: string;
  email: string;
  phone?: string;
  password?: string;
  role: Role;
  auths: IAuthProvider[];
  isBlocked?: boolean;
  transactionPin?: string;
}

export interface ILogin {
  email: string;
  password: string;
}

export enum Role {
  USER = "USER",
  ADMIN = "ADMIN",
}

export interface IAuthProvider {
  provider: "google" | "credentials";
  providerId: string;
}

/*============================================================================*/
// ─── Request body types ───────────────────────────────────────────
// These match the Joi validation schemas exactly

export interface RegisterDTO {
  fullName: string;
  email: string;
  phone: string;
  password: string;
  confirmPassword: string;
}

export interface LoginDTO {
  email: string;
  password: string;
  deviceId: string; // UUID generated by client on first install
  deviceName: string; // "Chrome on Windows 11"
}

export interface VerifyEmailDTO {
  email: string;
  code: string; // 6-digit OTP
}

export interface RefreshTokenDTO {
  // Refresh token comes from httpOnly cookie — not body
  // This DTO is empty intentionally; token is read from req.cookies
}

export interface ForgotPasswordDTO {
  email: string;
}

export interface ResetPasswordDTO {
  email: string;
  code: string; // OTP from email
  newPassword: string;
  confirmPassword: string;
}

export interface ChangePasswordDTO {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
}

// ─── Response types ───────────────────────────────────────────────

export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
}

export interface AuthUser {
  _id: string;
  fullName: string;
  email: string;
  phone: string;
  role: string;
  isEmailVerified: boolean;
  kycStatus: string;
}

export interface LoginResponse {
  user: AuthUser;
  tokens: AuthTokens;
}
