import dotenv from "dotenv";

dotenv.config();

export const env = {
  NODE_ENV: process.env.NODE_ENV!,
  PORT: Number(process.env.PORT!) || 5000,
  MONGO_URI: process.env.MONGO_URI!,
  SSL_STORE_ID: process.env.SSL_STORE_ID!,
  SSL_STORE_PASS: process.env.SSL_STORE_PASS!,
  BCRYPT_SALT_ROUND: process.env.BCRYPT_SALT_ROUND!,
  // JWT
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET!,
  JWT_ACCESS_EXPIRES: process.env.JWT_ACCESS_EXPIRES!,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET!,
  JWT_REFRESH_EXPIRES: process.env.JWT_REFRESH_EXPIRES!,

  // FRONTEND_URL
  FRONTEND_URL: process.env.FRONTEND_URL,

  // GOOGLE_CLIENT_SECRET
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
  EXPRESS_SESSION_SECRET: process.env.EXPRESS_SESSION_SECRET,
};
